---

- name: Configure user
  import_tasks: user_setup.yml
  become_user: root

- name: Set up aliases
  include_tasks:
    file: alias.yml
  
- name: Set vi mode for bash
  lineinfile:
    path: ~/.bashrc
    search_string: 'set -o vi'
    line: 'set -o vi'

