---

- name: Use vault file
  include_vars:
    file: sensitive.yml

- name: Configure user
  import_tasks: user_setup.yml
  become_user: root

- name: Create npm folder in .config
  file: 
   path: "~/.config/npm"
   recurse: yes
   state: directory

- name: Copy config files to destination
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "files/npmrc", dest: "~/.config/npm/npmrc" }

- name: Copy config templates to destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: ".bash_profile.j2", dest: "~/.bash_profile" }
    - { src: ".bashrc.j2", dest: "~/.bashrc" }
