---

- name: Setting up arch machine 
  hosts: localhost
  connection: local
  become: yes
  become_user: marco
  roles:
    - system-config
    - packages
    - xserver
    - window-manager
  vars:
    config_id: 2
