---

- name: Setting up arch machine 
  hosts: localhost
  connection: local
  become: yes
  become_user: marco
  roles:
    - system-config
    - { role: packages, become: yes, become_user: root}
    - xserver
    - window-manager
