---

- name: Clone nvim config repository
  git:
    repo: 'https://github.com/xRetry/nvim.git'
    dest: ~/.config/nvim

- name: Clone packer for nvim
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Install nvim plugins
  command: nvim -c "PackerSync" -c ":qa!"

