---

- name: Clone config repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
    - { repo: 'https://github.com/xRetry/nvim.git', dest: ~/.config/nvim }
    - { repo: 'https://github.com/xRetry/helix.git', dest: ~/.config/helix }
    - { repo: 'https://github.com/xRetry/wezterm.git', dest: ~/.config/wezterm }

- name: Install nvim plugins
  command: nvim --headless +'Lazy sync' +'sleep 20' +qall

- name: Create directories for config files
  file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "~/.config/tmux" }
    - { path: "~/.config/alacritty" }
    - { path: "~/.config/zellij" }
  
- name: Copy config files to destination
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "files/tmux.conf", dest: "~/.config/tmux/tmux.conf" }
    - { src: "files/config.kdl", dest: "~/.config/zellij/config.kdl" }

- name: Copy config templates to destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "alacritty.j2", dest: "~/.config/alacritty/alacritty.yml" }

- name: Start and enable network manager
  become: true
  become_user: root
  service:
    name: NetworkManager
    state: started
    enabled: yes

