---

- name: Clone nvim config repository
  git:
    repo: 'https://github.com/xRetry/nvim.git'
    dest: ~/.config/nvim

- name: Clone packer for nvim
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Install nvim plugins
  command: nvim -c "PackerSync" -c ":qa!"

- name: Clone helix config repository
  git:
    repo: 'https://github.com/xRetry/helix.git'
    dest: ~/.config/helix

- name: Create directories for config files
  file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "~/.config/tmux" }
    - { path: "~/.config/alacritty" }
  
- name: Copy config files to destination
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "files/tmux.conf", dest: "~/.config/tmux/tmux.conf" }
    - { src: "files/alacritty.yml", dest: "~/.config/alacritty/alacritty.yml" }

- name: Start and enable network manager
  service:
    name: NetworkManager
    state: started
    enabled: yes

