---

- name: Update pacman cache
  pacman:
    update_cache: true
  become: yes
  become_user: root

- name: Install util packages
  pacman:
    name: "{{ packages_utils }}"
    state: present

- name: Install development packages
  pacman:
    name: "{{ packages_dev }}"
    state: present

    
