---

- name: Install window manager
  pacman:
    name: "{{ packages_wm }}"
    state: present
  become: yes
  become_user: root

- name: Check if ~/.config/qtile is a git repo
  stat:
    path: ~/.config/qtile/.git
  register: git_file

- name: Delete ~/.config/qtile when no git repo
  file:
    state: absent
    path: ~/.config/qtile
  when: not git_file.stat.exists

- name: Clone qtile config repository
  git:
    repo: 'https://github.com/xRetry/qtile.git'
    dest: ~/.config/qtile
  when: not git_file.stat.exists

- name: Install psutil for qtile
  pip:
    name: psutil

- name: Set autostart for qtile
  lineinfile:
    path: ~/.xinitrc
    search_string: exec qtile start
    line: exec qtile start

