---

- name: Install Xorg
  pacman:
    name: "{{ packages_xorg }}"
    state: present
  become: yes
  become_user: root

- name: Copy XServer config files to destination
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "files/.xinitrc", dest: "~/.xinitrc" }
    - { src: "files/.xprofile", dest: "~/.xprofile" }

- name: Set autostart for Xserver
  lineinfile:
    path: ~/.bash_profile
    search_string: startx
    line: '[ -z "$DISPLAY" ] && [ $XDG_VTNR -eq 1 ] && startx'

