---

- name: Configure sudoers file
  lineinfile:
    path: /etc/sudoers
    regex: 'Cmnd_Alias\s*REBOOT'
    line: 'Cmnd_Alias    REBOOT = /sbin/halt, /sbin/reboot, /sbin/poweroff'
  become_user: root

- name: Configure sudoers file
  lineinfile:
    path: /etc/sudoers
    regex: '%wheel\s*ALL=(ALL:ALL)\*NOPASSWD'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: REBOOT'
  become_user: root

- name: Add marco to wheel group
  user:
    name: marco
    groups: wheel
    append: yes
  become_user: root

- name: Clone nvim config repository
  git:
    repo: 'https://github.com/xRetry/nvim.git'
    dest: ~/.config/nvim

- name: Clone packer for nvim
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Install nvim plugins
  command: nvim -c "PackerSync" -c ":qa!"

- name: Set vi mode for bash
  lineinfile:
    path: ~/.bashrc
    search_string: 'set -o vi'
    line: 'set -o vi'

- name: Set up aliases
  include_tasks:
    file: alias.yml
